"""Add Japanese learning models

Revision ID: e434a192c777
Revises: 
Create Date: 2025-08-18 00:28:02.034037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e434a192c777'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('japanese_sentence',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('japanese_text', sa.Text(), nullable=False),
    sa.Column('english_translation', sa.Text(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('difficulty_level', sa.Integer(), nullable=False),
    sa.Column('times_studied', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('hiragana_reading', sa.Text(), nullable=True),
    sa.Column('romaji_reading', sa.Text(), nullable=True),
    sa.Column('jlpt_level', sa.String(length=10), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('audio_url', sa.String(length=500), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('lesson_number', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('average_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_japanese_sentence_category'), 'japanese_sentence', ['category'], unique=False)
    op.create_index(op.f('ix_japanese_sentence_difficulty_level'), 'japanese_sentence', ['difficulty_level'], unique=False)
    op.create_index(op.f('ix_japanese_sentence_is_active'), 'japanese_sentence', ['is_active'], unique=False)
    op.create_index(op.f('ix_japanese_sentence_japanese_text'), 'japanese_sentence', ['japanese_text'], unique=False)
    op.create_index(op.f('ix_japanese_sentence_jlpt_level'), 'japanese_sentence', ['jlpt_level'], unique=False)
    op.create_index(op.f('ix_japanese_sentence_lesson_number'), 'japanese_sentence', ['lesson_number'], unique=False)
    op.create_table('tier',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('rate_limit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tier_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('limit', sa.Integer(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tier_id'], ['tier.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_rate_limit_tier_id'), 'rate_limit', ['tier_id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('profile_image_url', sa.String(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('native_language', sa.String(length=20), nullable=False),
    sa.Column('current_jlpt_level', sa.String(length=10), nullable=False),
    sa.Column('target_jlpt_level', sa.String(length=10), nullable=False),
    sa.Column('daily_study_goal', sa.Integer(), nullable=False),
    sa.Column('study_streak', sa.Integer(), nullable=False),
    sa.Column('best_streak', sa.Integer(), nullable=False),
    sa.Column('total_sentences_learned', sa.Integer(), nullable=False),
    sa.Column('total_study_time_minutes', sa.Integer(), nullable=False),
    sa.Column('preferred_study_time', sa.String(length=20), nullable=False),
    sa.Column('study_reminders_enabled', sa.Boolean(), nullable=False),
    sa.Column('audio_enabled', sa.Boolean(), nullable=False),
    sa.Column('furigana_enabled', sa.Boolean(), nullable=False),
    sa.Column('romaji_enabled', sa.Boolean(), nullable=False),
    sa.Column('difficulty_preference', sa.String(length=20), nullable=False),
    sa.Column('learning_preferences', sa.JSON(), nullable=True),
    sa.Column('study_categories', sa.JSON(), nullable=True),
    sa.Column('notification_settings', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tier_id', sa.Integer(), nullable=True),
    sa.Column('last_study_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tier_id'], ['tier.id'], ),
    sa.PrimaryKeyConstraint('id', 'uuid'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_user_current_jlpt_level'), 'user', ['current_jlpt_level'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_is_deleted'), 'user', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_user_last_study_date'), 'user', ['last_study_date'], unique=False)
    op.create_index(op.f('ix_user_native_language'), 'user', ['native_language'], unique=False)
    op.create_index(op.f('ix_user_target_jlpt_level'), 'user', ['target_jlpt_level'], unique=False)
    op.create_index(op.f('ix_user_tier_id'), 'user', ['tier_id'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('learning_session',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_type', sa.String(length=50), nullable=False),
    sa.Column('session_mode', sa.String(length=50), nullable=False),
    sa.Column('difficulty_level', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('planned_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('sentences_studied', sa.Integer(), nullable=False),
    sa.Column('correct_answers', sa.Integer(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('average_response_time_seconds', sa.Float(), nullable=True),
    sa.Column('session_score', sa.Float(), nullable=True),
    sa.Column('completion_status', sa.String(length=20), nullable=False),
    sa.Column('session_data', sa.JSON(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('statistics', sa.JSON(), nullable=True),
    sa.Column('jlpt_level_focus', sa.String(length=10), nullable=True),
    sa.Column('categories_studied', sa.JSON(), nullable=True),
    sa.Column('learning_goals', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_learning_session_completion_status'), 'learning_session', ['completion_status'], unique=False)
    op.create_index(op.f('ix_learning_session_difficulty_level'), 'learning_session', ['difficulty_level'], unique=False)
    op.create_index(op.f('ix_learning_session_ended_at'), 'learning_session', ['ended_at'], unique=False)
    op.create_index(op.f('ix_learning_session_jlpt_level_focus'), 'learning_session', ['jlpt_level_focus'], unique=False)
    op.create_index(op.f('ix_learning_session_session_mode'), 'learning_session', ['session_mode'], unique=False)
    op.create_index(op.f('ix_learning_session_session_type'), 'learning_session', ['session_type'], unique=False)
    op.create_index(op.f('ix_learning_session_started_at'), 'learning_session', ['started_at'], unique=False)
    op.create_index(op.f('ix_learning_session_user_id'), 'learning_session', ['user_id'], unique=False)
    op.create_table('ocr_record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('detected_language', sa.String(length=50), nullable=True),
    sa.Column('processing_time_seconds', sa.Float(), nullable=True),
    sa.Column('ocr_engine', sa.String(length=50), nullable=False),
    sa.Column('ocr_version', sa.String(length=50), nullable=True),
    sa.Column('processing_status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('bounding_boxes', sa.JSON(), nullable=True),
    sa.Column('text_regions', sa.JSON(), nullable=True),
    sa.Column('added_to_study', sa.Boolean(), nullable=False),
    sa.Column('sentence_id', sa.Integer(), nullable=True),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['sentence_id'], ['japanese_sentence.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_ocr_record_added_to_study'), 'ocr_record', ['added_to_study'], unique=False)
    op.create_index(op.f('ix_ocr_record_processing_status'), 'ocr_record', ['processing_status'], unique=False)
    op.create_index(op.f('ix_ocr_record_sentence_id'), 'ocr_record', ['sentence_id'], unique=False)
    op.create_index(op.f('ix_ocr_record_user_id'), 'ocr_record', ['user_id'], unique=False)
    op.create_table('post',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=False),
    sa.Column('text', sa.String(length=63206), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('media_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', 'uuid'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_post_created_by_user_id'), 'post', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_post_is_deleted'), 'post', ['is_deleted'], unique=False)
    op.create_table('user_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sentence_id', sa.Integer(), nullable=False),
    sa.Column('repetition_count', sa.Integer(), nullable=False),
    sa.Column('easiness_factor', sa.Float(), nullable=False),
    sa.Column('interval_days', sa.Integer(), nullable=False),
    sa.Column('next_review_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('correct_answers', sa.Integer(), nullable=False),
    sa.Column('total_attempts', sa.Integer(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('best_streak', sa.Integer(), nullable=False),
    sa.Column('study_status', sa.String(length=20), nullable=False),
    sa.Column('mastery_level', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_studied', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_correct', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['sentence_id'], ['japanese_sentence.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_user_progress_last_studied'), 'user_progress', ['last_studied'], unique=False)
    op.create_index(op.f('ix_user_progress_mastery_level'), 'user_progress', ['mastery_level'], unique=False)
    op.create_index(op.f('ix_user_progress_sentence_id'), 'user_progress', ['sentence_id'], unique=False)
    op.create_index(op.f('ix_user_progress_study_status'), 'user_progress', ['study_status'], unique=False)
    op.create_index(op.f('ix_user_progress_user_id'), 'user_progress', ['user_id'], unique=False)
    op.create_table('audio_record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('audio_file_path', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('audio_format', sa.String(length=20), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('practice_mode', sa.String(length=50), nullable=False),
    sa.Column('processing_status', sa.String(length=20), nullable=False),
    sa.Column('stt_engine', sa.String(length=50), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sentence_id', sa.Integer(), nullable=True),
    sa.Column('study_session_id', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('transcribed_text', sa.Text(), nullable=True),
    sa.Column('original_text', sa.Text(), nullable=True),
    sa.Column('transcription_confidence', sa.Float(), nullable=True),
    sa.Column('pronunciation_score', sa.Float(), nullable=True),
    sa.Column('phonetic_accuracy', sa.Float(), nullable=True),
    sa.Column('fluency_score', sa.Float(), nullable=True),
    sa.Column('timing_score', sa.Float(), nullable=True),
    sa.Column('feedback_text', sa.Text(), nullable=True),
    sa.Column('phoneme_analysis', sa.JSON(), nullable=True),
    sa.Column('improvement_suggestions', sa.JSON(), nullable=True),
    sa.Column('processing_time_seconds', sa.Float(), nullable=True),
    sa.Column('stt_model', sa.String(length=50), nullable=True),
    sa.Column('analysis_engine', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['sentence_id'], ['japanese_sentence.id'], ),
    sa.ForeignKeyConstraint(['study_session_id'], ['learning_session.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_audio_record_processing_status'), 'audio_record', ['processing_status'], unique=False)
    op.create_index(op.f('ix_audio_record_sentence_id'), 'audio_record', ['sentence_id'], unique=False)
    op.create_index(op.f('ix_audio_record_study_session_id'), 'audio_record', ['study_session_id'], unique=False)
    op.create_index(op.f('ix_audio_record_user_id'), 'audio_record', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audio_record_user_id'), table_name='audio_record')
    op.drop_index(op.f('ix_audio_record_study_session_id'), table_name='audio_record')
    op.drop_index(op.f('ix_audio_record_sentence_id'), table_name='audio_record')
    op.drop_index(op.f('ix_audio_record_processing_status'), table_name='audio_record')
    op.drop_table('audio_record')
    op.drop_index(op.f('ix_user_progress_user_id'), table_name='user_progress')
    op.drop_index(op.f('ix_user_progress_study_status'), table_name='user_progress')
    op.drop_index(op.f('ix_user_progress_sentence_id'), table_name='user_progress')
    op.drop_index(op.f('ix_user_progress_mastery_level'), table_name='user_progress')
    op.drop_index(op.f('ix_user_progress_last_studied'), table_name='user_progress')
    op.drop_table('user_progress')
    op.drop_index(op.f('ix_post_is_deleted'), table_name='post')
    op.drop_index(op.f('ix_post_created_by_user_id'), table_name='post')
    op.drop_table('post')
    op.drop_index(op.f('ix_ocr_record_user_id'), table_name='ocr_record')
    op.drop_index(op.f('ix_ocr_record_sentence_id'), table_name='ocr_record')
    op.drop_index(op.f('ix_ocr_record_processing_status'), table_name='ocr_record')
    op.drop_index(op.f('ix_ocr_record_added_to_study'), table_name='ocr_record')
    op.drop_table('ocr_record')
    op.drop_index(op.f('ix_learning_session_user_id'), table_name='learning_session')
    op.drop_index(op.f('ix_learning_session_started_at'), table_name='learning_session')
    op.drop_index(op.f('ix_learning_session_session_type'), table_name='learning_session')
    op.drop_index(op.f('ix_learning_session_session_mode'), table_name='learning_session')
    op.drop_index(op.f('ix_learning_session_jlpt_level_focus'), table_name='learning_session')
    op.drop_index(op.f('ix_learning_session_ended_at'), table_name='learning_session')
    op.drop_index(op.f('ix_learning_session_difficulty_level'), table_name='learning_session')
    op.drop_index(op.f('ix_learning_session_completion_status'), table_name='learning_session')
    op.drop_table('learning_session')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_tier_id'), table_name='user')
    op.drop_index(op.f('ix_user_target_jlpt_level'), table_name='user')
    op.drop_index(op.f('ix_user_native_language'), table_name='user')
    op.drop_index(op.f('ix_user_last_study_date'), table_name='user')
    op.drop_index(op.f('ix_user_is_deleted'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_current_jlpt_level'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_rate_limit_tier_id'), table_name='rate_limit')
    op.drop_table('rate_limit')
    op.drop_table('tier')
    op.drop_index(op.f('ix_japanese_sentence_lesson_number'), table_name='japanese_sentence')
    op.drop_index(op.f('ix_japanese_sentence_jlpt_level'), table_name='japanese_sentence')
    op.drop_index(op.f('ix_japanese_sentence_japanese_text'), table_name='japanese_sentence')
    op.drop_index(op.f('ix_japanese_sentence_is_active'), table_name='japanese_sentence')
    op.drop_index(op.f('ix_japanese_sentence_difficulty_level'), table_name='japanese_sentence')
    op.drop_index(op.f('ix_japanese_sentence_category'), table_name='japanese_sentence')
    op.drop_table('japanese_sentence')
    # ### end Alembic commands ###
